### PR TITLE
fix(if/philip_pal/mem_map): Fix description of tmr.mode.trig_edge

### PR DESCRIPTION
**Pull request by ngandrass**
Triggering on falling edges requires setting `tmr.mode.trig_edge` to `2`. However, it was documented as `1` instead.

This PR updates the documentation accordingly.

### CODE REVIEW

**Review by MrKevinWeiss — COMMENTED** [review]
Maybe also change it in the config

```diff
diff --git a/FW/MMM/PHiLIP_config.json b/FW/MMM/PHiLIP_config.json
index e3179ff..1f039a7 100644
--- a/FW/MMM/PHiLIP_config.json
+++ b/FW/MMM/PHiLIP_config.json
@@ -3215,7 +3215,7 @@
                     "access": 1,
                     "bit_offset": 2,
                     "bits": 2,
-                    "description": "0:both - 1:rising - 1:falling",
+                    "description": "0:both - 1:rising - 2:falling",
                     "name": [
                         "tmr",
                         "mode",
```

**Comment by MrKevinWeiss** [comment]
Very nice catch and thanks for the PR.  If you want I can  also do this but I would rather give you credit.

**Comment by ngandrass** [comment]
Good point, thanks! I updated the commit accordingly :)

**Review by MrKevinWeiss — APPROVED** [review]
ACK!

**Pull request merged**
