### PR TITLE
Fix typos found with codespell

### PR DESCRIPTION
**Pull request by yegorich**

### CODE REVIEW

**Comment by MrKevinWeiss** [comment]
I would like to add the spell check to the CI, what settings did you use since I couldn't find all the errors you did?

**Comment by yegorich** [comment]
Just the default ones:

    codespell -q 3

**Comment by MrKevinWeiss** [comment]
Is it OK if we use #68 since it is up-to-date and has the MMM regenerated as well as uses codespell in the CI now.

**Comment by MrKevinWeiss** [comment]
I think we can close as #68 is merged.  Thanks for pointing out codespell!

**Comment by yegorich** [comment]
So let's close it.

**Pull request closed without merging**
